// This file is auto-generated by @hey-api/openapi-ts

export const VehicleRequestSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string'
        },
        brand: {
            type: 'string'
        },
        model: {
            type: 'string'
        },
        year: {
            type: 'integer',
            format: 'int32'
        },
        rentalRate: {
            type: 'number'
        },
        seats: {
            type: 'integer',
            format: 'int32'
        },
        fuelType: {
            type: 'string'
        },
        image: {
            type: 'string',
            format: 'binary'
        },
        availabilityStatus: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        transmission: {
            type: 'string'
        },
        features: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        discount: {
            type: 'number'
        }
    },
    required: ['brand', 'fuelType', 'model', 'rentalRate', 'seats', 'type', 'year']
} as const;

export const VehicleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        type: {
            type: 'string'
        },
        brand: {
            type: 'string'
        },
        model: {
            type: 'string'
        },
        year: {
            type: 'integer',
            format: 'int32'
        },
        seats: {
            type: 'integer',
            format: 'int32'
        },
        fuelType: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        transmission: {
            type: 'string'
        },
        features: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        discount: {
            type: 'number'
        },
        rental_rate: {
            type: 'number'
        },
        availability_status: {
            type: 'string'
        },
        image_url: {
            type: 'string'
        },
        registration_date: {
            type: 'string',
            format: 'date'
        },
        discounted_price: {
            type: 'number'
        }
    }
} as const;

export const BookingStatusUpdateRequestSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        }
    },
    required: ['status']
} as const;

export const BookingResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        vehicleId: {
            type: 'string'
        },
        vehicleBrand: {
            type: 'string'
        },
        vehicleModel: {
            type: 'string'
        },
        vehicleType: {
            type: 'string'
        },
        vehicleImageUrl: {
            type: 'string'
        },
        vehicleRentalRate: {
            type: 'number'
        },
        customerId: {
            type: 'string'
        },
        customerName: {
            type: 'string'
        },
        customerEmail: {
            type: 'string'
        },
        startDate: {
            type: 'string',
            format: 'date'
        },
        endDate: {
            type: 'string',
            format: 'date'
        },
        rentalDays: {
            type: 'integer',
            format: 'int32'
        },
        totalCost: {
            type: 'number'
        },
        status: {
            type: 'string'
        },
        confirmationRef: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserRegistrationRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        phone_number: {
            type: 'string'
        }
    },
    required: ['email', 'full_name', 'password']
} as const;

export const UserResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED']
        },
        address: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        phone_number: {
            type: 'string'
        }
    }
} as const;

export const BookingRequestSchema = {
    type: 'object',
    properties: {
        vehicleId: {
            type: 'string',
            format: 'uuid'
        },
        startDate: {
            type: 'string',
            format: 'date'
        },
        endDate: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['endDate', 'startDate', 'vehicleId']
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const AuthTokenSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        tokenType: {
            type: 'string'
        },
        expiresIn: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const UpdateProfileRequestSchema = {
    type: 'object',
    properties: {
        address: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        phone_number: {
            type: 'string'
        }
    }
} as const;

export const VehiclePageSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/VehicleResponse'
            }
        },
        page: {
            type: 'integer',
            format: 'int32'
        },
        size: {
            type: 'integer',
            format: 'int32'
        },
        totalElements: {
            type: 'integer',
            format: 'int64'
        },
        totalPages: {
            type: 'integer',
            format: 'int32'
        },
        last: {
            type: 'boolean'
        }
    }
} as const;

export const PageBookingResponseSchema = {
    type: 'object',
    properties: {
        totalElements: {
            type: 'integer',
            format: 'int64'
        },
        totalPages: {
            type: 'integer',
            format: 'int32'
        },
        first: {
            type: 'boolean'
        },
        last: {
            type: 'boolean'
        },
        size: {
            type: 'integer',
            format: 'int32'
        },
        content: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BookingResponse'
            }
        },
        number: {
            type: 'integer',
            format: 'int32'
        },
        sort: {
            '$ref': '#/components/schemas/SortObject'
        },
        numberOfElements: {
            type: 'integer',
            format: 'int32'
        },
        pageable: {
            '$ref': '#/components/schemas/PageableObject'
        },
        empty: {
            type: 'boolean'
        }
    }
} as const;

export const PageableObjectSchema = {
    type: 'object',
    properties: {
        offset: {
            type: 'integer',
            format: 'int64'
        },
        sort: {
            '$ref': '#/components/schemas/SortObject'
        },
        pageNumber: {
            type: 'integer',
            format: 'int32'
        },
        pageSize: {
            type: 'integer',
            format: 'int32'
        },
        paged: {
            type: 'boolean'
        },
        unpaged: {
            type: 'boolean'
        }
    }
} as const;

export const SortObjectSchema = {
    type: 'object',
    properties: {
        empty: {
            type: 'boolean'
        },
        sorted: {
            type: 'boolean'
        },
        unsorted: {
            type: 'boolean'
        }
    }
} as const;