// This file is auto-generated by @hey-api/openapi-ts

export const UserRegistrationRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        phone_number: {
            type: 'string'
        }
    },
    required: ['email', 'full_name', 'password']
} as const;

export const UserResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED']
        },
        address: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        phone_number: {
            type: 'string'
        }
    }
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const AuthTokenSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        tokenType: {
            type: 'string'
        },
        expiresIn: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const UpdateProfileRequestSchema = {
    type: 'object',
    properties: {
        address: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        phone_number: {
            type: 'string'
        }
    }
} as const;