// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginData, LoginResponse, UpdateBookingStatusData, UpdateBookingStatusResponse, GetMyBookingsResponse, CreateBookingData, CreateBookingResponse, GetBookingByIdData, GetBookingByIdResponse, CancelBookingData, CancelBookingResponse, GetAllBookingsData, GetAllBookingsResponse, UploadImageData, UploadImageResponse, RegisterData, RegisterResponse, GetCurrentUserResponse, DeleteProfileResponse, UpdateProfileData, UpdateProfileResponse, UpdateVehicleData, UpdateVehicleResponse, DeleteVehicleData, DeleteVehicleResponse, ListVehiclesData, ListVehiclesResponse, CreateVehicleData, CreateVehicleResponse, BrowseVehiclesData, BrowseVehiclesResponse, GetVehicleData, GetVehicleResponse, GetVehicleSuggestionsResponse, ToggleFavouriteData, ToggleFavouriteResponse, GetFavouritesResponse, GetFavouriteIdsResponse, GetPopularVehiclesData, GetPopularVehiclesResponse } from './types.gen';

export class AuthControllerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AuthToken OK
     * @throws ApiError
     */
    public static login(data: LoginData): CancelablePromise<LoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class BookingControllerService {
    /**
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns BookingResponse OK
     * @throws ApiError
     */
    public static updateBookingStatus(data: UpdateBookingStatusData): CancelablePromise<UpdateBookingStatusResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/admin/bookings/{id}/status',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @returns BookingResponse OK
     * @throws ApiError
     */
    public static getMyBookings(): CancelablePromise<GetMyBookingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/bookings'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns BookingResponse Created
     * @throws ApiError
     */
    public static createBooking(data: CreateBookingData): CancelablePromise<CreateBookingResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/bookings',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns BookingResponse OK
     * @throws ApiError
     */
    public static getBookingById(data: GetBookingByIdData): CancelablePromise<GetBookingByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/bookings/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns void No Content
     * @throws ApiError
     */
    public static cancelBooking(data: CancelBookingData): CancelablePromise<CancelBookingResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/bookings/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.page
     * @param data.size
     * @param data.status
     * @returns PageBookingResponse OK
     * @throws ApiError
     */
    public static getAllBookings(data: GetAllBookingsData = {}): CancelablePromise<GetAllBookingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/bookings',
            query: {
                page: data.page,
                size: data.size,
                status: data.status
            }
        });
    }
}

export class FileUploadControllerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns string OK
     * @throws ApiError
     */
    public static uploadImage(data: UploadImageData = {}): CancelablePromise<UploadImageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/admin/upload/image',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class UserControllerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserResponse Created
     * @throws ApiError
     */
    public static register(data: RegisterData): CancelablePromise<RegisterResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static getCurrentUser(): CancelablePromise<GetCurrentUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteProfile(): CancelablePromise<DeleteProfileResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static updateProfile(data: UpdateProfileData): CancelablePromise<UpdateProfileResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class VehicleControllerService {
    /**
     * @param data The data for the request.
     * @param data.id
     * @param data.formData
     * @returns VehicleResponse OK
     * @throws ApiError
     */
    public static updateVehicle(data: UpdateVehicleData): CancelablePromise<UpdateVehicleResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/admin/vehicles/{id}',
            path: {
                id: data.id
            },
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteVehicle(data: DeleteVehicleData): CancelablePromise<DeleteVehicleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/admin/vehicles/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.page
     * @param data.size
     * @param data.type
     * @param data.brand
     * @param data.status
     * @param data.search
     * @param data.sortBy
     * @returns VehiclePage OK
     * @throws ApiError
     */
    public static listVehicles(data: ListVehiclesData = {}): CancelablePromise<ListVehiclesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/vehicles',
            query: {
                page: data.page,
                size: data.size,
                type: data.type,
                brand: data.brand,
                status: data.status,
                search: data.search,
                sort_by: data.sortBy
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.formData
     * @returns VehicleResponse Created
     * @throws ApiError
     */
    public static createVehicle(data: CreateVehicleData = {}): CancelablePromise<CreateVehicleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/admin/vehicles',
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.page
     * @param data.size
     * @param data.type
     * @param data.brand
     * @param data.search
     * @param data.sortBy
     * @param data.minPrice
     * @param data.maxPrice
     * @param data.availableFrom
     * @param data.availableTo
     * @returns VehiclePage OK
     * @throws ApiError
     */
    public static browseVehicles(data: BrowseVehiclesData = {}): CancelablePromise<BrowseVehiclesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vehicles',
            query: {
                page: data.page,
                size: data.size,
                type: data.type,
                brand: data.brand,
                search: data.search,
                sort_by: data.sortBy,
                min_price: data.minPrice,
                max_price: data.maxPrice,
                available_from: data.availableFrom,
                available_to: data.availableTo
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns VehicleResponse OK
     * @throws ApiError
     */
    public static getVehicle(data: GetVehicleData): CancelablePromise<GetVehicleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vehicles/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.limit
     * @returns VehicleResponse OK
     * @throws ApiError
     */
    public static getPopularVehicles(data: GetPopularVehiclesData = {}): CancelablePromise<GetPopularVehiclesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vehicles/popular',
            query: {
                limit: data.limit
            }
        });
    }

    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getVehicleSuggestions(): CancelablePromise<GetVehicleSuggestionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vehicles/suggestions'
        });
    }
}

export class FavouriteControllerService {
    /**
     * @param data The data for the request.
     * @param data.vehicleId
     * @returns FavouriteToggleResponse OK
     * @throws ApiError
     */
    public static toggle(data: ToggleFavouriteData): CancelablePromise<ToggleFavouriteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/favourites/{vehicleId}',
            path: {
                vehicleId: data.vehicleId
            }
        });
    }

    /**
     * @returns VehicleResponse OK
     * @throws ApiError
     */
    public static getFavourites(): CancelablePromise<GetFavouritesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/favourites'
        });
    }

    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getFavouriteIds(): CancelablePromise<GetFavouriteIdsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/favourites/ids'
        });
    }
}