// This file is auto-generated by @hey-api/openapi-ts

export type AuthToken = {
    accessToken?: string;
    tokenType?: string;
    expiresIn?: number;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type UpdateProfileRequest = {
    address?: string;
    full_name?: string;
    phone_number?: string;
};

export type UserRegistrationRequest = {
    email: string;
    password: string;
    full_name: string;
    phone_number?: string;
};

export type UserResponse = {
    id?: string;
    email?: string;
    status?: 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'SUSPENDED';
    address?: string;
    roles?: Array<(string)>;
    full_name?: string;
    phone_number?: string;
};

export type status = 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'SUSPENDED';

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse = (AuthToken);

export type RegisterData = {
    requestBody: UserRegistrationRequest;
};

export type RegisterResponse = (UserResponse);

export type GetCurrentUserResponse = (UserResponse);

export type DeleteProfileResponse = (void);

export type UpdateProfileData = {
    requestBody: UpdateProfileRequest;
};

export type UpdateProfileResponse = (UserResponse);