// This file is auto-generated by @hey-api/openapi-ts

export type AuthToken = {
    accessToken?: string;
    tokenType?: string;
    expiresIn?: number;
};

export type BookingRequest = {
    vehicleId: string;
    startDate: string;
    endDate: string;
};

export type BookingResponse = {
    id?: string;
    vehicleId?: string;
    vehicleBrand?: string;
    vehicleModel?: string;
    vehicleType?: string;
    vehicleImageUrl?: string;
    vehicleRentalRate?: number;
    customerId?: string;
    customerName?: string;
    customerEmail?: string;
    startDate?: string;
    endDate?: string;
    rentalDays?: number;
    totalCost?: number;
    status?: string;
    confirmationRef?: string;
    createdAt?: string;
};

export type BookingStatusUpdateRequest = {
    status: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    pageNumber?: number;
    pageSize?: number;
    paged?: boolean;
    unpaged?: boolean;
};

export type PageBookingResponse = {
    totalElements?: number;
    totalPages?: number;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<BookingResponse>;
    number?: number;
    sort?: SortObject;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type SortObject = {
    empty?: boolean;
    sorted?: boolean;
    unsorted?: boolean;
};

export type UpdateProfileRequest = {
    address?: string;
    full_name?: string;
    phone_number?: string;
};

export type UserRegistrationRequest = {
    email: string;
    password: string;
    full_name: string;
    phone_number?: string;
};

export type UserResponse = {
    id?: string;
    email?: string;
    status?: 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'SUSPENDED';
    address?: string;
    role?: string;
    full_name?: string;
    phone_number?: string;
};

export type status = 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'SUSPENDED';

export type VehiclePage = {
    content?: Array<VehicleResponse>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    last?: boolean;
};

export type VehicleRequest = {
    type: string;
    brand: string;
    model: string;
    year: number;
    rentalRate: number;
    seats: number;
    fuelType: string;
    image?: (Blob | File);
    availabilityStatus?: string;
    description?: string;
    transmission?: string;
    features?: Array<(string)>;
    discount?: number;
};

export type VehicleResponse = {
    id?: string;
    type?: string;
    brand?: string;
    model?: string;
    year?: number;
    seats?: number;
    fuelType?: string;
    description?: string;
    transmission?: string;
    features?: Array<(string)>;
    discount?: number;
    rental_rate?: number;
    availability_status?: string;
    image_url?: string;
    registration_date?: string;
    discounted_price?: number;
};

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse = (AuthToken);

export type UpdateBookingStatusData = {
    id: string;
    requestBody: BookingStatusUpdateRequest;
};

export type UpdateBookingStatusResponse = (BookingResponse);

export type GetMyBookingsResponse = (Array<BookingResponse>);

export type CreateBookingData = {
    requestBody: BookingRequest;
};

export type CreateBookingResponse = (BookingResponse);

export type GetBookingByIdData = {
    id: string;
};

export type GetBookingByIdResponse = (BookingResponse);

export type CancelBookingData = {
    id: string;
};

export type CancelBookingResponse = (void);

export type GetAllBookingsData = {
    page?: number;
    size?: number;
    status?: string;
};

export type GetAllBookingsResponse = (PageBookingResponse);

export type UploadImageData = {
    requestBody?: {
        file: (Blob | File);
    };
};

export type UploadImageResponse = ({
    [key: string]: (string);
});

export type RegisterData = {
    requestBody: UserRegistrationRequest;
};

export type RegisterResponse = (UserResponse);

export type GetCurrentUserResponse = (UserResponse);

export type DeleteProfileResponse = (void);

export type UpdateProfileData = {
    requestBody: UpdateProfileRequest;
};

export type UpdateProfileResponse = (UserResponse);

export type UpdateVehicleData = {
    formData?: VehicleRequest;
    id: string;
};

export type UpdateVehicleResponse = (VehicleResponse);

export type DeleteVehicleData = {
    id: string;
};

export type DeleteVehicleResponse = (void);

export type ListVehiclesData = {
    brand?: string;
    page?: number;
    search?: string;
    size?: number;
    sortBy?: string;
    status?: string;
    type?: string;
};

export type ListVehiclesResponse = (VehiclePage);

export type CreateVehicleData = {
    formData?: VehicleRequest;
};

export type CreateVehicleResponse = (VehicleResponse);

export type BrowseVehiclesData = {
    availableFrom?: string;
    availableTo?: string;
    brand?: string;
    maxPrice?: number;
    minPrice?: number;
    page?: number;
    search?: string;
    size?: number;
    sortBy?: string;
    type?: string;
};

export type BrowseVehiclesResponse = (VehiclePage);

export type GetVehicleData = {
    id: string;
};

export type GetVehicleResponse = (VehicleResponse);

export type GetVehicleSuggestionsResponse = ({
    [key: string]: Array<(string)>;
});

export type FavouriteToggleResponse = {
    favourited: boolean;
};

export type ToggleFavouriteData = {
    vehicleId: string;
};

export type ToggleFavouriteResponse = (FavouriteToggleResponse);

export type GetFavouritesResponse = (Array<VehicleResponse>);

export type GetFavouriteIdsResponse = (Array<string>);

export type GetPopularVehiclesData = {
    limit?: number;
};

export type GetPopularVehiclesResponse = (Array<VehicleResponse>);