/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VehiclesIdRouteImport } from './routes/vehicles/$id'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutFavouritesRouteImport } from './routes/_layout/favourites'
import { Route as LayoutBookingsRouteImport } from './routes/_layout/bookings'
import { Route as VehiclesIdIndexRouteImport } from './routes/vehicles/$id/index'
import { Route as VehiclesIdBookRouteImport } from './routes/vehicles/$id/book'
import { Route as AdminLayoutVehiclesRouteImport } from './routes/admin/_layout/vehicles'
import { Route as AdminLayoutTransactionsRouteImport } from './routes/admin/_layout/transactions'
import { Route as AdminLayoutReportsRouteImport } from './routes/admin/_layout/reports'
import { Route as AdminLayoutMaintenanceRouteImport } from './routes/admin/_layout/maintenance'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as AdminLayoutBookingsRouteImport } from './routes/admin/_layout/bookings'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFavouritesRoute = LayoutFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBookingsRoute = LayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => LayoutRoute,
} as any)
const VehiclesIdIndexRoute = VehiclesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesIdRoute,
} as any)
const VehiclesIdBookRoute = VehiclesIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => VehiclesIdRoute,
} as any)
const AdminLayoutVehiclesRoute = AdminLayoutVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTransactionsRoute = AdminLayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReportsRoute = AdminLayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMaintenanceRoute = AdminLayoutMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsRoute = AdminLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bookings': typeof LayoutBookingsRoute
  '/favourites': typeof LayoutFavouritesRoute
  '/profile': typeof LayoutProfileRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/maintenance': typeof AdminLayoutMaintenanceRoute
  '/admin/reports': typeof AdminLayoutReportsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/vehicles': typeof AdminLayoutVehiclesRoute
  '/vehicles/$id/book': typeof VehiclesIdBookRoute
  '/vehicles/$id/': typeof VehiclesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bookings': typeof LayoutBookingsRoute
  '/favourites': typeof LayoutFavouritesRoute
  '/profile': typeof LayoutProfileRoute
  '/admin': typeof AdminIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/maintenance': typeof AdminLayoutMaintenanceRoute
  '/admin/reports': typeof AdminLayoutReportsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/vehicles': typeof AdminLayoutVehiclesRoute
  '/vehicles/$id/book': typeof VehiclesIdBookRoute
  '/vehicles/$id': typeof VehiclesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/bookings': typeof LayoutBookingsRoute
  '/_layout/favourites': typeof LayoutFavouritesRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/admin/_layout/bookings': typeof AdminLayoutBookingsRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/maintenance': typeof AdminLayoutMaintenanceRoute
  '/admin/_layout/reports': typeof AdminLayoutReportsRoute
  '/admin/_layout/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/_layout/vehicles': typeof AdminLayoutVehiclesRoute
  '/vehicles/$id/book': typeof VehiclesIdBookRoute
  '/vehicles/$id/': typeof VehiclesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/bookings'
    | '/favourites'
    | '/profile'
    | '/admin'
    | '/vehicles/$id'
    | '/admin/'
    | '/vehicles'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/maintenance'
    | '/admin/reports'
    | '/admin/transactions'
    | '/admin/vehicles'
    | '/vehicles/$id/book'
    | '/vehicles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/bookings'
    | '/favourites'
    | '/profile'
    | '/admin'
    | '/vehicles'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/maintenance'
    | '/admin/reports'
    | '/admin/transactions'
    | '/admin/vehicles'
    | '/vehicles/$id/book'
    | '/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/bookings'
    | '/_layout/favourites'
    | '/_layout/profile'
    | '/admin'
    | '/admin/_layout'
    | '/vehicles/$id'
    | '/admin/'
    | '/vehicles/'
    | '/admin/_layout/bookings'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/maintenance'
    | '/admin/_layout/reports'
    | '/admin/_layout/transactions'
    | '/admin/_layout/vehicles'
    | '/vehicles/$id/book'
    | '/vehicles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminRoute: typeof AdminRouteWithChildren
  VehiclesIdRoute: typeof VehiclesIdRouteWithChildren
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/favourites': {
      id: '/_layout/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof LayoutFavouritesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bookings': {
      id: '/_layout/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof LayoutBookingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/vehicles/$id/': {
      id: '/vehicles/$id/'
      path: '/'
      fullPath: '/vehicles/$id/'
      preLoaderRoute: typeof VehiclesIdIndexRouteImport
      parentRoute: typeof VehiclesIdRoute
    }
    '/vehicles/$id/book': {
      id: '/vehicles/$id/book'
      path: '/book'
      fullPath: '/vehicles/$id/book'
      preLoaderRoute: typeof VehiclesIdBookRouteImport
      parentRoute: typeof VehiclesIdRoute
    }
    '/admin/_layout/vehicles': {
      id: '/admin/_layout/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminLayoutVehiclesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/transactions': {
      id: '/admin/_layout/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminLayoutTransactionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports': {
      id: '/admin/_layout/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminLayoutReportsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/maintenance': {
      id: '/admin/_layout/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminLayoutMaintenanceRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings': {
      id: '/admin/_layout/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminLayoutBookingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBookingsRoute: typeof LayoutBookingsRoute
  LayoutFavouritesRoute: typeof LayoutFavouritesRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBookingsRoute: LayoutBookingsRoute,
  LayoutFavouritesRoute: LayoutFavouritesRoute,
  LayoutProfileRoute: LayoutProfileRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutBookingsRoute: typeof AdminLayoutBookingsRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutMaintenanceRoute: typeof AdminLayoutMaintenanceRoute
  AdminLayoutReportsRoute: typeof AdminLayoutReportsRoute
  AdminLayoutTransactionsRoute: typeof AdminLayoutTransactionsRoute
  AdminLayoutVehiclesRoute: typeof AdminLayoutVehiclesRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutBookingsRoute: AdminLayoutBookingsRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutMaintenanceRoute: AdminLayoutMaintenanceRoute,
  AdminLayoutReportsRoute: AdminLayoutReportsRoute,
  AdminLayoutTransactionsRoute: AdminLayoutTransactionsRoute,
  AdminLayoutVehiclesRoute: AdminLayoutVehiclesRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VehiclesIdRouteChildren {
  VehiclesIdBookRoute: typeof VehiclesIdBookRoute
  VehiclesIdIndexRoute: typeof VehiclesIdIndexRoute
}

const VehiclesIdRouteChildren: VehiclesIdRouteChildren = {
  VehiclesIdBookRoute: VehiclesIdBookRoute,
  VehiclesIdIndexRoute: VehiclesIdIndexRoute,
}

const VehiclesIdRouteWithChildren = VehiclesIdRoute._addFileChildren(
  VehiclesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminRoute: AdminRouteWithChildren,
  VehiclesIdRoute: VehiclesIdRouteWithChildren,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
