/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutFavouritesRouteImport } from './routes/_layout/favourites'
import { Route as LayoutBookingsRouteImport } from './routes/_layout/bookings'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as AdminLayoutBookingsRouteImport } from './routes/admin/_layout/bookings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFavouritesRoute = LayoutFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBookingsRoute = LayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsRoute = AdminLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bookings': typeof LayoutBookingsRoute
  '/favourites': typeof LayoutFavouritesRoute
  '/profile': typeof LayoutProfileRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bookings': typeof LayoutBookingsRoute
  '/favourites': typeof LayoutFavouritesRoute
  '/profile': typeof LayoutProfileRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/cars': typeof CarsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/bookings': typeof LayoutBookingsRoute
  '/_layout/favourites': typeof LayoutFavouritesRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/_layout/bookings': typeof AdminLayoutBookingsRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/login'
    | '/signup'
    | '/bookings'
    | '/favourites'
    | '/profile'
    | '/admin'
    | '/admin/'
    | '/admin/bookings'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cars'
    | '/login'
    | '/signup'
    | '/bookings'
    | '/favourites'
    | '/profile'
    | '/admin'
    | '/admin/bookings'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/cars'
    | '/login'
    | '/signup'
    | '/_layout/bookings'
    | '/_layout/favourites'
    | '/_layout/profile'
    | '/admin/_layout'
    | '/admin/'
    | '/admin/_layout/bookings'
    | '/admin/_layout/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  CarsRoute: typeof CarsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/favourites': {
      id: '/_layout/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof LayoutFavouritesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bookings': {
      id: '/_layout/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof LayoutBookingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings': {
      id: '/admin/_layout/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminLayoutBookingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBookingsRoute: typeof LayoutBookingsRoute
  LayoutFavouritesRoute: typeof LayoutFavouritesRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBookingsRoute: LayoutBookingsRoute,
  LayoutFavouritesRoute: LayoutFavouritesRoute,
  LayoutProfileRoute: LayoutProfileRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  CarsRoute: CarsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
